### ISSUE TITLE
DNS_PROBE_FINISHED_NXDOMAIN

### ISSUE THREAD

**Issue by grallc** [thezeroalpha/lecture-notes#2]
Hi!
Just trying to access the lectures notes, but I can't access reach the new domain name...
`lectures.alex.balgavy.eu’s server IP address could not be found.`

My DNS are up-to-date.

Thanks!

**Comment by thezeroalpha** [comment]
Hey, thanks for letting me know! You caught me between server migrations, I'm moving everything to my own VPS so I'm setting up the DNS records, those take some time to propagate. But everything should be functional later today, or tomorrow at the latest. Now that I know people actually use these I'll be more careful 😁

**Comment by thezeroalpha** [comment]
@grallc should be working now, if you still have issues please let me know. Also I'll post to [this RSS feed](https://blog.alex.balgavy.eu/atom.xml) next time I'm planning any downtime.

**Comment by grallc** [comment]
Thanks! I can now access the website.
However, I cannot access the different courses
Whenever I click on a course name, it redirects to me `https://www.alex.balgavy.eu/{course}` with a `404 Not Found` error.
https://www.alex.balgavy.eu/dsa-notes

**Comment by thezeroalpha** [comment]
Alright, seems like that was due to some legacy settings on github pages. Is it working for you now?
That is, not the link you posted, but the links from [lectures.alex.balgavy.eu](https://lectures.alex.balgavy.eu). Most of them should redirect you to a github.io page, because I haven't moved all of the pages across to the new setup yet.

**Comment by grallc** [comment]
It works with some courses !
So I guess I'll just wait that you have finished to move evrything!

**Comment by thezeroalpha** [comment]
I've transferred data structures & algorithms notes over, should be working now at [https://lectures.alex.balgavy.eu/dsa-notes/](https://lectures.alex.balgavy.eu/dsa-notes/). I'm closing this issue, let me know if you have any other problems. I'll be transferring the rest of the courses from Github over the next 1-2 weeks.
